#!/usr/bin/env bash
# 67-stop_me_if_you_can: sends SIGTERM to 7-highlander

# Get the PID(s) of 7-highlander
pids=$(pgrep -f "7-highlander")

# Send SIGTERM to each PID
for pid in $pids; do
    kill -15 "$pid"
done
