#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and reacts to SIGTERM by printing a message

handle_sigterm() {
    echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
